[project]
name = "StressLess-backend"
version = "0.1.0"
dependencies = [
  "fastapi[all]",
  "sqlmodel",
  "psycopg[binary]",
  "psycopg2-binary",
  "python-jose[cryptography]",
  "bcrypt",
  "python-dotenv",
  "librosa",
]

[tool.fastapi]
app = "main:app"